name: flutter_app
description: A new Flutter application.
version: 2.0.6+20

environment:
  sdk: ">=2.1.0 <3.0.0"
#dependencies:下面列出的就是项目所需要的包
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #---初始化三方库，在公司能加载出来-----------------------
  flutter_webview_plugin: ^0.3.5
  flutter_web_view: ^0.0.6
#  fluro: ^1.4.0
  shared_preferences: ^0.5.3+1
  #^2.0.0
  localstorage: ^2.0.0
  http: ^0.12.0+2
  #App信息
  package_info: ^0.4.0+4
   #设备
  device_info: ^0.4.0+1
  #toast
  fluttertoast: ^3.1.0
  #下拉刷新
  pull_to_refresh: ^1.4.4
  flutter_easyrefresh: ^1.2.7
   #选择器
#  flutter_picker:
#      git: git://github.com/yangyxd/flutter_picker.git
#  flutter_picker: ^1.0.11

#  json_serializable: ^3.0.0
#  json_annotation: ^2.4.0
#  json_rpc_2: ^2.1.0
#或者可以
#   fluro:
#     git: git://github.com/theyakka/fluro.git
  #"^"表明使用小版本的更新，保存会自动下载这个需要的包
#  scoped_model:
#  intl:
  # http:

#  crypto:
  #---------------------------------


  #查找文件系统上常用位置
  #^1.1.0
#  path_provider:
#  #云存储#
#  firebase_storage: ^3.0.1


#  #视频
#  video_player: ^0.10.1+3
#  #网络管理
#  connectivity: ^0.4.3+2
#  #通讯-组件之间通讯
#  flutter_bloc: ^0.17.0
#  #权限操作
#  permission_handler: ^3.1.0
#  #数据传递-给所有请求它的后代flutter_redux
#  flutter_redux: ^0.5.3
#  #数据库管理
#  sqflite: ^1.1.5
#  #自动大小text
#  auto_size_text: ^2.0.1
#  #通知 报androidx.core:core错误
##  flutter_local_notifications: ^0.7.1+3
#  #报androidx.core:core错误
##  location: ^2.0.0
#
#  #左滑删除-右滑删除
#  flutter_slidable: ^0.5.3
#  #toast
#  #Android平台上启动任意意图
#  android_intent: ^0.3.0+2
#  #pdf
#  flutter_full_pdf_viewer: ^1.0.4
#  #图片剪切
#  image_cropper: ^1.0.2
#  #toast
#  oktoast: ^2.1.8
#    #弹出框
#  rflutter_alert: ^1.0.2
#  #动态链接-提示用户安装应用
#  firebase_dynamic_links: ^0.4.0+2
#  #二维码
#  barcode_scan: ^1.0.0
#  #访问摄像头
#  camera: ^0.5.2+1
#  #缓存管理器
#  flutter_cache_manager: ^0.3.2
#  #加载框-loadding
#  progress_hud: ^1.1.0
#  #加载框-图片缩放
#  flutter_advanced_networkimage: ^0.4.15
#  #键盘操作-软键盘
#  keyboard_visibility: ^0.5.6
#  #萌层 ^2.2.2
#  intro_slider:
#  #日历
#  flutter_calendar_carousel: ^1.3.17
#  #日期控件-时间控件-日历控件table_calendar
#  table_calendar: ^1.2.2
#  #日期选择器
#  flutter_cupertino_date_picker: ^1.0.2
#  #时间选择器-日期选择器底部弹出
#  flutter_datetime_picker: ^1.2.1
#  #视频播放器
#  chewie: ^0.9.7
#  #数据传递
#  provide: ^1.0.2
#  #文件管理-打开文件
#  open_file: ^2.0.3
#  #下拉刷新-粘性-回弹
#  flutter_easyrefresh: ^1.2.7
#  #选择器-城市选择器-自定义内容选择器city_pickers
#  city_pickers: ^0.1.16
#  #选择相册里面的图片
#  multi_image_picker: ^4.3.3
#  #圆形进度条-条形进度条
#  percent_indicator: ^2.1.0
#  #拍照
#  photo: ^0.3.3
#  #拍照
#  photo_manager: ^0.3.3






#    shared_preferences:

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#scoped_model:
#intl:
#  http:
#  json_annotation:
#  json_serializable:
#  crypto:
#  flutter_webview_plugin:
#    shared_preferences:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/a.jpeg
    - images/food01.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
